# Generated by Django 2.0.3 on 2018-03-20 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0008_auto_20180320_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorit',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialapp.Posts'),
        ),
    ]
