# Generated by Django 2.0.3 on 2018-03-20 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialapp', '0011_auto_20180320_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='firstname', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='favorit',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialapp.Posts'),
        ),
    ]
