# Generated by Django 2.0.3 on 2018-03-20 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0012_auto_20180320_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.AlterField(
            model_name='favorit',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialapp.Posts'),
        ),
    ]
